//{{NO_DEPENDENCIES}}
// fichier Include Microsoft Visual C++.
// Utilisé par PatternXP.rc
//
#define IDD_FIRST_NOTE                  3
#define IDD_SORTBYNOTE                  10
#define IDD_SORTBYDISTANCE              11
#define IDD_SHARP                       100
#define IDD_FLAT                        101
#define IDD_MAJOR                       102
#define IDD_DIALOGBAR                   103
#define IDD_MINOR                       103
#define IDD_RADIOMINOR                  104
#define IDD_RADIOMAJOR                  105
#define IDC_NP_NAME                     1011
#define IDC_NP_LENGTH                   1058
#define IDR_TOOLBAR_EXT                 1999
#define IDR_TOOLBAR                     2000
#define IDD_COLUMN_DIALOG               2003
#define IDC_TREE_STATIC                 2003
#define IDC_COMBO1                      2005
#define IDB_TREE_IMAGES                 2006
#define IDC_LIST1                       2006
#define IDC_COMBO3                      2006
#define IDB_BITMAP1                     2007
#define IDB_TOOLBAR24                   2007
#define IDC_CHECK1                      2007
#define IDC_MIDI_EDIT                   2007
#define IDC_FONT_BUTTON                 2008
#define IDC_COLUMNS_BUTTON              2009
#define IDC_EDIT1                       2009
#define IDC_BAR_COMBO                   2010
#define IDC_COMBO2                      2010
#define IDC_MISC_BUTTON                 2011
#define IDC_COMBO4                      2011
#define IDC_HELP_CHECK                  2012
#define IDC_COMBO5                      2012
#define IDC_PASTE_BUTTON                2013
#define IDC_BUTTON1                     2013
#define IDC_CUT_BUTTON                  2014
#define IDC_MFCBUTTON1                  2014
#define IDC_COPY_BUTTON                 2015
#define IDC_GENERATE                    2015
#define IDC_CLEAR_BUTTON                2022
#define IDC_IMPORT_BUTTON               2023
#define IDC_EXPORT_BUTTON               2024
#define IDC_SHRINK_BUTTON               2025
#define IDC_INFLATE_COMBO               2026
#define IDC_EXPAND_BUTTON               2027
#define IDC_ADDOFF_BUTTON               2028
#define IDC_UPOFF_BUTTON                2029
#define IDC_DOWNOFF_BUTTON              2030
#define IDC_TOOLBAR_BUTTON              2031
#define IDC_HUMANIZE_BUTTON             2032
#define IDC_HUMANIZE_EDIT               2033
#define IDC_HUMANIZE_EMPTY              2034
#define IDC_INSERT_CHORD                2035
#define IDC_CHORD_COMBO                 2036
#define IDC_CHECK_CHORD_ONCE            2037
#define IDC_CHORD_FILE_BUTTON           2038
#define IDC_INTERPOLATE_BUTTON          2039
#define IDC_INTERPOLATE_COMBO           2040
#define IDC_REVERSE_BUTTON              2041
#define IDC_MIRROR_BUTTON               2042
#define IDC_PARAMETERS_BUTTON           2043
#define IDC_BT_INSROW                   2044
#define IDC_BT_DELROW                   2045
#define IDC_TONAL_COMBO                 2046
#define IDC_TONAL_BUTTON                2047
#define IDC_TRANSPOSE_COMBO             2048
#define IDC_MINUS_BUTTON                2049
#define IDC_PLUS_BUTTON                 2050
#define IDC_ARPEGGIO_COMBO              2051
#define IDC_ARPEGGIO_SAVE               2052
#define IDC_DLG_CHORD                   2053
#define IDC_ARPEGGIO_LOAD               2054
#define IDC_TRANSPOSE                   2055
#define IDC_SAVE_PROGRESSION            2056



#define IDD_PARAMETERS_DIALOG           3000
#define ID_PERSISTENT_SELECTION         3001
#define ID_PERSISTENT_PLAYPOS           3002
#define ID_USE_TOOLBAR                  3003
#define ID_IMPORT_AUTO_RESIZE           3004
#define ID_CHORD_AUTO_REFRESH           3005
#define ID_PGUPDOWN_DISABLED            3006
#define ID_HOME_DISABLED                3007
#define ID_DRAW_ROW_BUTTON              3008
#define ID_GRAPHICALWIDTH               3009
#define ID_GRAPHICALROW                 3011
#define IDD_MINMAXLIMITER_DIALOG        3012
#define IDD_CHORD_EXPERT_DIALOG         4000
#define IDD_TONAL_DIALOG                5000
#define IDD_SAVE_ARPEGGIO_DIALOG        6000
#define ID_COLUMNS_BUTTON               32773
#define ID_SELECT_FONT                  32774
#define ID_CHECK_MIDI_BT                32775
#define ID_COMBO_BAR_BT                 32776
#define ID_BT_COPY                      32777
#define ID_BT_CUT                       32778
#define ID_BT_PASTE                     32779
#define ID_BT_MERGE                     32780
#define ID_BT_CLEAROFF                  32781
#define ID_BT_ADDOFF                    32782
#define ID_BT_UPOFF                     32783
#define ID_BT_DOWNOFF                   32784
#define ID_BT_IMPORT                    32785
#define ID_BT_EXPORT                    32786
#define ID_BT_SHRINK                    32787
#define ID_COMBO_SHRINK_BT              32788
#define ID_BT_EXPAND                    32789
#define ID_CHECK_HELP_BT                32790
#define ID_COMBO_BAR_LABEL_BT           32791
#define ID_CHECK_TOOLBAR_BT             32792
#define ID_BT_HUMANIZE                  32793
#define ID_HUMANIZE_DELTA_BT            32794
#define ID_CHECK_HUMANIZE_EMPTY_BT      32795
#define ID_BT_INSERT_CHORD              32796
#define ID_COMBO_CHORD_BT               32797
#define ID_BT_CHORD_FILE                32798
#define ID_CHECK_CHORD_ONCE_BT          32799
#define ID_BT_INTERPOLATE               32800
#define ID_INTERPOLATE_PARAM_BT         32801
#define ID_BT_REVERSE                   32802
#define ID_BT_MIRROR                    32803
#define ID_PARAMETERS_BUTTON            32804
#define ID_BT_INSROW                    32805
#define ID_BT_DELROW                    32806
#define ID_LABEL_TONAL_BT               32807
#define ID_COMBO_TONAL_BT               32808
#define ID_TONAL_BT                     32809
#define ID_BT_MINUS                     32810
#define ID_COMBO_TRANSPOSE_BT           32811
#define ID_BT_PLUS                      32812
#define ID_COMBO_ARPEGGIO_BT            32813
#define ID_BT_ARPEGGIO_SAVE             32814
#define ID_BT_DLG_CHORD                 32815
#define ID_BT_ARPEGGIO_LOAD             32816
#define ID_MIN_MAX_LIMITER              32817
#define ID_CHECK_MIDI                   33775
#define ID_COMBO_BAR                    33776
#define ID_COMBO_SHRINK                 33788
#define ID_CHECK_HELP                   33790
#define ID_COMBO_BAR_LABEL              33791
#define ID_CHECK_TOOLBAR                33792
#define ID_HUMANIZE_DELTA               33794
#define ID_CHECK_HUMANIZE_EMPTY         33795
#define ID_COMBO_CHORD                  33797
#define ID_CHECK_CHORD_ONCE             33799
#define ID_INTERPOLATE_PARAM            33801
#define ID_LABEL_TONAL                  33807
#define ID_COMBO_TONAL                  33808
#define ID_COMBO_TRANSPOSE              33811
#define ID_COMBO_ARPEGGIO               33813
#define ID_SAVE_PROGRESSION             33814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2016
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         2016
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
